import { pgTable, text, timestamp, uuid, uniqueIndex, index } from "drizzle-orm/pg-core";
import { users } from "./auth";

/**
 * Auth tables are owned by Better Auth and generated by its CLI; these reference
 * `users.id` directly now that they exist.
 */

/**
 * Every customer has exactly one organization, including individuals (a personal org
 * of one). v1 exposes a single login per org; `memberships` exists so adding seats for
 * planners later is a feature, not a migration.
 */
export const organizations = pgTable(
  "organizations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    ownerUserId: text("owner_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** Defaults inherited by new events. */
    defaultLocale: text("default_locale").notNull().default("es-MX"),
    defaultTimezone: text("default_timezone").notNull().default("America/Mexico_City"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("organizations_slug_key").on(t.slug),
    index("organizations_owner_idx").on(t.ownerUserId),
  ],
);

export const memberships = pgTable(
  "memberships",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: text("role").$type<"owner" | "admin" | "member">().notNull().default("owner"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("memberships_org_user_key").on(t.orgId, t.userId)],
);
